backend:
  name: git-gateway
  branch: main

media_folder: "images"

media_library:
  name: uploadcare
  config:
    publicKey: fbb66349001efbc7e5ce
    multiple: true
  settings:

collections:
  - name: "visualArt"
    label: "Visual Art" 
    folder: "_posts/visualArt"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "string", default: "default" }
      - { label: "Categories", name: "categories", widget: "string", default: "visualArt" }
      - { label: "Title", name: "title", widget: "string", required: false }
      - { label: "Year", name: "year", widget: "string", required: false }
      - { label: "Materials", name: "materials", widget: "string", required: false}
      - { label: "Dimensions", name: "dimensions", widget: "string", required: false }
      - { label: "Images", name: "images", widget: "image" }
  - name: "film"
    label: "Film" 
    folder: "_posts/film"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "string", default: "default" }
      - { label: "Categories", name: "categories", widget: "string", default: "film" }
      - { label: "Title", name: "title", widget: "string", required: false }
      - { label: "Year", name: "year", widget: "string", required: false }
      - { label: "Materials", name: "materials", widget: "string", required: false}
      - { label: "Film Link", name: "filmLink", widget: "string", required: false}
      - { label: "Images", name: "images", widget: "image" }
  - name: "about"
    label: "About" 
    folder: "_posts/about"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "string", default: "default" }
      - { label: "Categories", name: "categories", widget: "string", default: "about" }
      - { label: "Title", name: "title", widget: "string", required: false }
      - { label: "Images", name: "images", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
      